### ISSUE TITLE
1.21.1-py27_0 package with zero dependencies breaks openssl 1.1.1 resolve

### ISSUE THREAD

**Issue by s22chan** [conda-forge/urllib3-feedstock#18]
Issue:

The missing (cryptography) package dependencies were rectified in build number 1, but anaconda can actually resolve to build 0 for dependencies.

This means that with Conda-forge in your channel list:

```sh
conda create -n test "openssl==1.1.1" "python==2.7.15" "urllib3==1.21.1"
```
```
Solving environment: done

## Package Plan ##

  added / updated specs:
    - openssl==1.1.1
    - python==2.7.15
    - urllib3==1.21.1
```

You will then later get the following error as it tries to dlopen the older lib crypto libs:
```
VerificationError: importing '/root/.conda/envs/gk_build/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_4ed9e37dx4000d087.so': libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

Without Conda-forge:

```sh
conda create -n test "openssl==1.1.1" "python==2.7.15" "urllib3==1.21.1"
```
```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - openssl==1.1.1
  - urllib3==1.21.1 -> cryptography[version='>=1.3.4'] -> openssl=1.0
Use "conda info <package>" to see the dependencies for each package.
```

Solution:
Is it possible to delete the offending packages from anaconda cloud? Thanks.

**Comment by ocefpaf** [comment]
Done! Can you check and try again?

https://anaconda.org/conda-forge/urllib3/files?version=1.21.1

**Comment by s22chan** [comment]
Thanks for the quick response, but looks like there's even older versions without pinning, so I think it's easiest if I enforce urllib3 >=1.23 on consuming side.

Thanks!
