### ISSUE TITLE
brotlipy?

### ISSUE THREAD

**Issue by paugier** [conda-forge/urllib3-feedstock#25]
I encountered an error using mercurial + hg-git, which uses dulwich, which uses urllib3 about brotlipy missing.

After `conda install brotlipy`, the problem was solved.

Indeed, urllib3 uses in some cases brotlipy https://github.com/urllib3/urllib3/blob/master/setup.py#L66

Would it be possible to had it (https://github.com/conda-forge/brotlipy-feedstock) as a dependency of the urllib3 conda package?

**Comment by ocefpaf** [comment]
`brotlipy` is an optional dependency and `conda` does not handle that gracefully yet. The @conda-forge/urllib3 decided to package only the "secure" optional deps for `urllib3` b/c those are more widely used, `brotlipy` seems to be an specific case and we don't want to bloat the package. As you already notice installing it solves the problem.
