### ISSUE TITLE
1.24.3 contains a back-ported security fix, should be built

### ISSUE THREAD

**Issue by tjd2002** [conda-forge/urllib3-feedstock#26]
### Issue:
There is a security fix from the 1.25 branch released on the 1.24 branch (as 1.24.3). Some people are stuck on 1.24 (in particular because `requests` is not yet compatible with 1.25. https://github.com/kennethreitz/requests/issues/5065)

See release notes here:
https://pypi.org/project/urllib3/1.24.3/

**Comment by tjd2002** [comment]
Apparently this can be accomplished by creating a dedicated branch. 
https://github.com/conda-forge/conda-forge.github.io/issues/480

**Comment by ocefpaf** [comment]
If you send a PR (point it to `master` at first), I'll create the branch and merge it.

**Comment by tjd2002** [comment]
Thanks @ocefpaf !

**Comment by ocefpaf** [comment]
No problem. Thanks for reporting it and sending the PR!
