### ISSUE TITLE
missing 1.26.16 in conda forge

### ISSUE THREAD

**Issue by rcarpa** [conda-forge/urllib3-feedstock#72]
Hi, team, 

1.26.16 doesn't seem to have been uploaded to conda forge. It's probably because it was released after 2.0 and the bot ignored it. Could you please add it? 

Regards, 
Radu

**Comment by ocefpaf** [comment]
@rcarpa can you send a PR to it? past releases should be in  a branch and it is hard for us to maintain them, so any help is welcome.

**Comment by rcarpa** [comment]
Hi @ocefpaf, there is no branch right now for the 1.26.x line. Only for 1.24.x. Could you please create it so that I can open a PR against the new branch?

**Comment by ocefpaf** [comment]
Done. You can target v1.26.x now.
